title: "86Box"
description: "Emulator of x86-based machines"

github:
  is_project_page: true
  repository_name: 86Box
  repository_url: https://github.com/86Box/86Box
  owner_name: OBattler
  owner_url: https://github.com/OBattler
